server:
  port: 7011
spring:
  application:
    name: flowable-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.90.84:3306/flowable?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

logging:
  pattern:
    console: "%d - [%-5level] - %msg%n"
#  level: info
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
flowable:
#关闭定时任务JOB
  async-executor-activate: false


eureka:
  instance:
    instance-id: localhost:7011 #在eureka信息列表显示的主机名称
    prefer-ip-address: true #服务显示IP地址
  client: #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://localhost:8761/eureka/


#actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
info: #/actuator/info 自定义的info端点 否则是空的
    app:
      version: 1.0-SNAPSHOT
      artifactId: flowable-server
      name: flowable-server
