server:
  port: 7001
spring:
  application:
    name: zuul-gateway

eureka:
  instance:
    instance-id: localhost:7001 #在eureka信息列表显示的主机名称
    prefer-ip-address: true #服务显示IP地址
  client: #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*" #禁用所有服务名称进行访问
  routes: #路由映射配置
    community-provider-project: /project-proxy/**
    community-provider-team: /team-proxy/**
    flowable-server: /flowable-proxy/**
    consumer-feign: /feign-proxy/**
#  prefix:  /gateway  #设置前缀
#  ignored-services: sv-provider-project  #禁用某个服务名称进行访问

#actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
info: #/actuator/info 自定义的info端点 否则是空的
    app:
      version: 1.0-SNAPSHOT
      artifactId: zuul-gateway
      name: zuul-gateway
